openapi: 3.0.1
info:
  title: Fibonacci API
  version: v1
paths:
  /api/Fibonacci:
    get:
      tags:
        - Fibonacci
      parameters:
        - name: len
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
            text/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
components: { }