name: Deploy Azure APIM Core

on:  
  push:
    paths:
      - 'opsTeam/**'
  workflow_dispatch:

env:  
  LOCATION: 'eastus'
  BASE_REPO_URL: 'https://raw.githubusercontent.com/Keayoub/apimDevOps/main/opsTeam/'


jobs:
  deploy-dev:

    environment: DEV

    runs-on: ubuntu-latest
  
    steps:      
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                          
      - name: Deploy (Bicep) Template
        id: deployAzRes
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}    
          scope: subscription      
          region: ${{ env.LOCATION }}
          template: ./opsTeam/master.bicep
          parameters: environmentValue=dev rgName=${{ vars.RESOURCE_GROUP_NAME }} apimName=${{ vars.APIM_NAME }}  repoBaseUrl=${{ env.BASE_REPO_URL }} location=${{ env.LOCATION}} publisherEmail=${{ secrets.PUPLISHER_EMAIL }} publisherName=${{ secrets.PUBLISHER_NAME }}
             
  deploy-prod:
    needs: deploy-dev
          
    environment: PROD

    runs-on: ubuntu-latest
  
    steps:      
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                                
      - name: Deploy (Bicep) Template
        id: deployAzRes
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          scope: subscription      
          region: ${{ env.LOCATION }}
          template: ./opsTeam/master.bicep
          parameters: environmentValue=prod rgName=${{ vars.RESOURCE_GROUP_NAME }} apimName=${{ vars.APIM_NAME }} repoBaseUrl=${{ env.BASE_REPO_URL }}  location=${{ env.LOCATION}} publisherEmail=${{ secrets.PUPLISHER_EMAIL }} publisherName=${{ secrets.PUBLISHER_NAME }}      