name: Destroy Azure Resources

on:
  workflow_dispatch:

jobs:
  destroy-DEV:
    runs-on: ubuntu-latest
    environment: DEV   

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Resource Group
        run: |
          az group delete -n ${{ vars.RESOURCE_GROUP_NAME}} --yes
          az group delete -n ${{ vars.FIBONACCI_RESOURCE_GROUP}} --yes
          az group delete -n ${{ vars.WEATHER_RESOURCE_GROUP}} --yes

  destroy-PRDO:
    runs-on: ubuntu-latest
    environment: PROD
    needs:
      - destroy-DEV

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Resource Group
        run: |
          az group delete -n ${{ vars.RESOURCE_GROUP_NAME}} --yes
          az group delete -n ${{ vars.FIBONACCI_RESOURCE_GROUP}} --yes
          az group delete -n ${{ vars.WEATHER_RESOURCE_GROUP}} --yes
