name: Deploy Infra Fibonacci API

on:  
  push:
    paths:
      - 'fibonacciApi/infra/**'
  workflow_dispatch:

env:
  LOCATION: 'eastus'
  AZURE_WEBAPP_PACKAGE_PATH: 'artifact'

jobs:
  create-azure-resource-dev:
    
    environment: DEV
      
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        run: |
          az group create -n ${{ vars.FIBONACCI_RESOURCE_GROUP }} -l ${{ env.LOCATION }}

      - name: Build bicep template
        run: |
         bicep build ./fibonacciApi/infra/infra.bicep         
                          
      - name: Deploy Azure Resource Manager (ARM) Template
        id: armDeployment
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: '${{ secrets.SUBSCRIPTION_ID }}'
          resourceGroupName: ${{ vars.FIBONACCI_RESOURCE_GROUP }}
          template: ./fibonacciApi/infra/infra.json
          parameters: location=${{ env.LOCATION}} webappName=${{ vars.FIBONACCI_WEBAPP_NAME }} appServicePlanName=${{ vars.FIBONACCI_WEBAPP_NAME }}-asp }}

      - uses: gliech/create-github-secret-action@v1
        name: Write Web App URL FIBONACCI API Dev URL
        with:
          name: WEBAPP_FIBONACCI_URL_DEV
          value: ${{ steps.armDeployment.outputs.url }}
          pa_token: ${{ secrets.PA_TOKEN }}       
     
  create-azure-resource-prod:
    needs:             
      - create-azure-resource-dev   

    environment: PROD  
            
    runs-on: ubuntu-latest
          
    steps:      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        run: |
          az group create -n ${{ vars.FIBONACCI_RESOURCE_GROUP }} -l ${{ env.LOCATION }}

      - name: Build bicep template
        run: |
         bicep build ./fibonacciApi/infra/infra.bicep         

      - name: Deploy Azure Resource Manager Bicep Template
        id: armDeployment
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.FIBONACCI_RESOURCE_GROUP }}
          template: ./fibonacciApi/infra/infra.json
          parameters: location=${{ env.LOCATION}} webappname=${{ vars.FIBONACCI_WEBAPP_NAME }} appServicePlanName=${{ vars.FIBONACCI_WEBAPP_NAME }}-asp }}


      - name: Write Web App URL FIBONACCI API Prod URL
        uses: gliech/create-github-secret-action@v1      
        with:
          name: WEBAPP_FIBONACCI_URL_PROD
          value: ${{ steps.armDeployment.outputs.url }}
          pa_token: ${{ secrets.PA_TOKEN }}   