name: Deploy Fibonacci API

on:  
  push:
    paths:
      - 'fibonacciApi/src/**'
      - 'fibonacciApi/template/**'
  workflow_dispatch:

env:
  LOCATION: 'eastus'
  AZURE_WEBAPP_PACKAGE_PATH: 'artifact'

jobs:
  build-api:        
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dotnet 3.3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: dotnet build and publish
        working-directory: ./fibonacciApi/src
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/fibonacciApi'          
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:          
          name: artifact        
          path: './fibonacciApi/src/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/fibonacciApi'
        
  deploy-dev:        
    needs: 
      - build-api   
    
    environment: DEV
    
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:          
          name: artifact

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    

      - name: 'Deploy Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.FIBONACCI_WEBAPP_NAME }}
      
      - name: Deploy API in APIM        
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./fibonacciApi/template/api.bicep
          parameters: WebUrl=${{ secrets.WEBAPP_FIBONACCI_URL_DEV }} ApimServiceName=${{ vars.APIM_NAME}}                    

  deploy-prod:        
    needs:             
      - deploy-dev

    environment: PROD
    
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: artifact

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    

      - name: 'Deploy Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.FIBONACCI_WEBAPP_NAME }}   
          
      - name: Deploy API in APIM        
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./fibonacciApi/template/api.bicep
          parameters: WebUrl=${{ secrets.WEBAPP_FIBONACCI_URL_PROD }} ApimServiceName=${{ vars.APIM_NAME}}               
