name: Deploy Weather API

on:  
  push:
    paths:
      - 'weatherApi/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: 'apim-weather-rg'
  LOCATION: 'eastus'

jobs:
  create-azure-resource:
    runs-on: ubuntu-latest
  
    steps:      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}
          
                
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./weatherApi/infra/infra.json
          parameters: location=${{ env.LOCATION}}
      
